"""Apply hand-made title/abstract decisions to the screening table.

Usage:
    python framework/apply_screen_decisions.py docs/literature-review/screen_decisions_*.csv

Each decisions file holds one row per record that a person actually read:

    record_id,screen_ta,exclusion_reason,note      (title/abstract screen)
    record_id,screen_ft,exclusion_reason,note      (full-text screen)

Which column the file uses decides which stage is being recorded, so both screens run
through one script and neither can quietly overwrite the other.

The decisions live in their own file, in git, rather than being typed into the big screening
table, for three reasons: the screening table is regenerated by the merge script and would
overwrite them; a decisions file is small enough to review in a pull request; and it records
who decided what, separately from the machine triage.

Any record in a decisions file that the screening table does not contain is an error, not a
warning - it means the two files have drifted apart.
"""

from __future__ import annotations

import csv
import sys
from collections import Counter
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCREENING_CSV = REPO_ROOT / "data" / "search" / "screening.csv"

VALID_DECISIONS = {"include", "exclude", "maybe"}
VALID_REASONS = {
    "not_human", "not_unloading_model", "duration_too_short", "no_muscle_outcome",
    "upper_limb_only", "no_baseline_or_followup", "disease_causes_wasting",
    "review_or_editorial", "duplicate_report", "no_full_text", "language",
}

csv.field_size_limit(10_000_000)


def load_decisions(paths: list) -> dict:
    decisions = {}
    for path in paths:
        with Path(path).open(encoding="utf-8-sig", newline="") as handle:
            reader = csv.DictReader(handle)
            stage = "screen_ft" if "screen_ft" in (reader.fieldnames or []) else "screen_ta"
            for row in reader:
                record_id = row["record_id"].strip()
                decision = row[stage].strip()
                reason = row["exclusion_reason"].strip()
                if decision not in VALID_DECISIONS:
                    raise SystemExit(f"{path}: '{decision}' is not a valid {stage} for {record_id}")
                if decision == "exclude" and reason not in VALID_REASONS:
                    raise SystemExit(f"{path}: '{reason}' is not one of the fixed exclusion codes ({record_id})")
                if decision != "exclude" and reason:
                    raise SystemExit(f"{path}: {record_id} is '{decision}' but carries an exclusion reason")
                # Keyed by record *and* stage: a study screened at title/abstract and again at full
                # text has two decisions, and neither may overwrite the other.
                decisions[(record_id, stage)] = (decision, reason, row.get("note", "").strip(),
                                                Path(path).name)
    return decisions


def main() -> int:
    paths = sys.argv[1:]
    if not paths:
        print(__doc__)
        return 2

    decisions = load_decisions(paths)

    with SCREENING_CSV.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        columns = list(reader.fieldnames or [])
        rows = list(reader)

    by_id = {row["record_id"]: row for row in rows}
    missing = sorted({record for record, _stage in decisions} - set(by_id))
    if missing:
        raise SystemExit(f"{len(missing)} decided records are not in the screening table: {missing[:5]}")

    applied = Counter()
    today = date.today().isoformat()
    for (record_id, stage), (decision, reason, note, source) in decisions.items():
        row = by_id[record_id]
        row[stage] = decision
        if reason or stage == "screen_ta":
            row["exclusion_reason"] = reason
        row["screener"] = "read_by_hand"
        row["screen_date"] = today
        if note:
            row["notes"] = "; ".join(part for part in (row.get("notes", ""), note) if part)
        applied[f"{stage}: {decision}"] += 1

    # Everything in the priority bucket that nobody decided is explicitly a `maybe`,
    # so an unread record is never mistaken for a screened one.
    for row in rows:
        if row.get("triage") == "priority" and not row["screen_ta"]:
            row["screen_ta"] = "maybe"
            row["screener"] = "read_by_hand"
            row["screen_date"] = today
            applied["maybe (priority, needs full text)"] += 1

    with SCREENING_CSV.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)

    print(f"{len(decisions)} decisions applied from {len(paths)} file(s)")
    for decision, count in applied.most_common():
        print(f"  {decision:34s} {count:4d}")

    included = [r for r in rows if r["screen_ta"] == "include" and r["screen_ft"] != "exclude"]
    print(f"\nincluded at title/abstract: {len(included)}")
    print("  full text in Europe PMC:", sum(1 for r in included if r["in_epmc"] == "yes"))
    print("  open access:            ", sum(1 for r in included if r["is_oa"] == "yes"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
