"""Package the project into one zip for a collaborator.

    python framework/make_handoff.py
    python framework/make_handoff.py --no-exports    # leave the Scopus/WoS exports out

Everything a collaborator needs to check, rerun or extend the work: the extraction tables,
the search and screening record, every full text on disk, the framework code, and the plan.
A MANIFEST.md is generated at the root of the archive describing what each folder holds and
which files carry redistribution conditions - it is written from the real file counts, so it
cannot describe an archive different from the one it ships in.

The git history is not included. It is recoverable from the remote and would double the size.
"""

from __future__ import annotations

import argparse
import zipfile
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Directory prefixes and exact files that never travel.
SKIP_DIRS = {".git", "__pycache__", ".ipynb_checkpoints", ".venv", "venv", "node_modules"}
SKIP_SUFFIXES = {".pyc", ".stackdump", ".zip"}
SKIP_NAMES = {".DS_Store", "Thumbs.db", ".access_cache.json", ".gitkeep"}

# Bulk database exports. Scopus and Web of Science licence terms restrict redistributing
# exported records, so these are separable behind a flag rather than silently bundled.
LICENSED = "docs/literature-review/exports"

SECTIONS = [
    ("data/raw", "The extraction tables. `extraction_qaragoz.csv` is the trustworthy core; "
                 "`extraction_partial.csv` holds records from papers that published only a headline "
                 "number; `extraction_figures.csv` holds values recovered from charts."),
    ("data/schema.md", "The frozen extraction contract. Read this before changing any row."),
    ("data/cohorts.csv", "The campaign map. Papers sharing participants share a `cohort_id`, "
                         "which is the unit cross-validation is grouped by."),
    ("data/search", "The full search record: every retrieved record, every screening decision "
                    "with its reason, and the per-paper digests written during full-text review."),
    ("docs/literature-review", "Search strategy per database, PRISMA counts, the extraction queue, "
                               "and the per-paper reasons parked studies could not be extracted."),
    ("docs/data_report.html", "A browsable inventory of all 580 rows. Open it in a browser."),
    ("resources", "Every full text obtained: publisher PDFs, Europe PMC XML, and the figure pages "
                  "rendered for digitisation."),
    ("framework", "The code. Every table in `data/` is regenerated by these scripts rather than "
                  "edited by hand."),
    ("PLAN.md", "The work plan and schedule."),
    ("README.md", "Decisions log: what is committed, the branch model, and the claim the talk exists to prove."),
    ("proposal.md", "The accepted DGLRM abstract. This is the contract; it is never edited."),
    ("DGLRM_HDBR_Muscle_Atrophy_ML_Dataset.xlsx",
     "A separate, earlier dataset built from the 15 supplied PDFs. Disjoint from the extraction "
     "tables at paper level (no shared DOI), but three of its cohorts are the same campaigns as "
     "ours. Its `atrophy_pct` is positive for loss - the opposite sign convention to `pct_change`."),
]


def collect(include_exports: bool) -> list[Path]:
    files = []
    for path in REPO_ROOT.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(REPO_ROOT)
        if SKIP_DIRS & set(relative.parts):
            continue
        if path.suffix in SKIP_SUFFIXES or path.name in SKIP_NAMES:
            continue
        if not include_exports and relative.as_posix().startswith(LICENSED):
            continue
        files.append(path)
    return sorted(files)


def manifest(files: list[Path], stem: str, include_exports: bool) -> str:
    def count(prefix: str) -> tuple[int, int]:
        chosen = [f for f in files if f.relative_to(REPO_ROOT).as_posix().startswith(prefix)]
        return len(chosen), sum(f.stat().st_size for f in chosen)

    def human(size: int) -> str:
        for unit in ("B", "KB", "MB"):
            if size < 1024 or unit == "MB":
                return f"{size:.0f} {unit}" if unit != "MB" else f"{size:.1f} MB"
            size /= 1024
        return ""

    pdfs = sum(1 for f in files if f.suffix.lower() == ".pdf")
    xml = sum(1 for f in files if f.suffix.lower() == ".xml")
    total = sum(f.stat().st_size for f in files)

    lines = [
        f"# {stem}",
        "",
        "From Bed Rest to Mars — a literature-derived machine learning framework for predicting",
        "lower-limb muscle atrophy in spaceflight analogues. DGLRM 2026.",
        "",
        f"Packaged {date.today().isoformat()} — {len(files)} files, {human(total)}, "
        f"including {pdfs} PDFs and {xml} XML full texts.",
        "",
        "## Where to start",
        "",
        "1. `README.md` — what was decided and why.",
        "2. `docs/data_report.html` — open in a browser; it explains what one row of the dataset is.",
        "3. `data/schema.md` — the rules every row obeys.",
        "4. `data/raw/extraction_qaragoz.csv` — the data itself.",
        "",
        "## What each part holds",
        "",
        "| Path | Files | Size | Contents |",
        "|---|---|---|---|",
    ]

    for prefix, description in SECTIONS:
        number, size = count(prefix)
        if not number:
            continue
        lines.append(f"| `{prefix}` | {number} | {human(size)} | {description} |")

    lines += [
        "",
        "## Conditions on two parts of this archive",
        "",
        "**`resources/`** contains publisher PDFs and full-text XML obtained through institutional",
        "access. They are included so the extraction can be checked against its sources. They are",
        "copyrighted material: use them to verify and extend this work, and do not redistribute them",
        "further or post them publicly.",
        "",
    ]

    if include_exports:
        number, size = count(LICENSED)
        lines += [
            f"**`{LICENSED}/`** ({number} files, {human(size)}) contains bulk records exported from",
            "Scopus and Web of Science. Both licences restrict redistributing exported records, which",
            "is why these files are kept out of the public repository. They are here so the search is",
            "reproducible without repeating it; treat them as internal to the project.",
            "",
        ]
    else:
        lines += [
            f"**`{LICENSED}/`** was deliberately left out of this archive, because Scopus and Web of",
            "Science licence terms restrict redistributing exported records. The search queries in",
            "`docs/literature-review/PLAN.md` reproduce them from any institutional account.",
            "",
        ]

    lines += [
        "## Rebuilding anything here",
        "",
        "Nothing in `data/` is maintained by hand. From the repository root:",
        "",
        "```",
        "python framework/merge_search_exports.py      # exports    -> data/search/all_records.csv",
        "python framework/extraction_report.py         # extraction -> data/raw/extraction_report.md",
        "python framework/build_data_report.py         # extraction -> docs/data_report.html",
        "```",
        "",
        "The git history is not in this archive; it lives at the project remote.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-exports", action="store_true",
                        help="omit the licensed Scopus and Web of Science bulk exports")
    parser.add_argument("--out", type=Path, default=None, help="output zip path")
    args = parser.parse_args()

    include_exports = not args.no_exports
    stem = f"DGLRM_handoff_{date.today().isoformat()}"
    target = args.out or REPO_ROOT / f"{stem}.zip"

    files = collect(include_exports)
    text = manifest(files, stem, include_exports)

    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        archive.writestr(f"{stem}/MANIFEST.md", text)
        for path in files:
            archive.write(path, f"{stem}/{path.relative_to(REPO_ROOT).as_posix()}")

    raw = sum(f.stat().st_size for f in files)
    packed = target.stat().st_size
    print(f"wrote {target}")
    print(f"  {len(files)} files, {raw / 1024 / 1024:.1f} MB raw -> "
          f"{packed / 1024 / 1024:.1f} MB zipped")
    print(f"  licensed exports: {'included' if include_exports else 'omitted'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
